config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout',
                                             sign_up: 'register' }

  get 'projects/new', to: 'projects#new'
  get 'projects/:id', to: 'projects#show'
  resources :projects, except: [:show] do
    put :sort, on: :collection
  end

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :body, :project_id, presence: true

  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |tech| tech['name'].blank? }
  has_many :blogs
  validates :title, :description, presence: true

  mount_uploader :image, ProjectUploader

  def self.by_position
    order("position ACS")
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  has_and_belongs_to_many :projects

  mount_uploader :icon, TechnologyUploader
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                          ##
  ############################################################################################

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def first_name
   self.name.split.first
  end

  def last_name
   self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  include DeviseWhitelist
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      flash.now[:errors] = @blog.errors.full_messages
      render :new
    end
  end

  def show
    @blogs = Blog.all
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      flash.now[:errors] = @blog.errors.full_messages
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :project_id)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
    @technologies = Technology.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :show, :destroy]
  before_action :set_techs, only: [:edit, :update]

  access all: [],
         user: [],
         site_admin: :all

  def index
    @projects = Project.by_position
  end

  def new
    @project = Project.new
  end

  def create
    @projects = Project.new(project_params)

    if @projects.save
      redirect_to root_path, notice: 'Project created'
    else
      flash.now[:errors] = @projects.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to root_path, notice: 'Project was successfully updated'
    else
      flash.now[:errors] = @project.errors.full_messages
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
    @project.destroy

    redirect_to root_path, notice: 'Project removed'
  end

  def sort
    params[:order].each do |key, value|
      Project.find(value[:id]).update(position: value[:position])
    end

    head :ok
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def set_techs
      @technologies = Technology.all
    end

    def project_params
      params.require(:project).permit(:title,
                                      :image,
                                      :description,
                                      technologies_attributes: [:id, :name, :icon, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  require 'redcarpet'
  require 'rouge'
  require 'rouge/plugins/redcarpet'

  class HTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet

    def block_code(code, language)
      Rouge.highlight(code, language || 'text', 'html')
    end
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" }
    }

    extensions = {
      autolink:           true,
      highlight:          true,
      superscript:        true,
      disable_indented_code_blocks: true,
      space_after_headers: true,
      fenced_code_blocks: true
    }

    #renderer = Redcarpet::Render::HTML.new(options)
    renderer = HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/blogs/_blog.html.erb
<script type="text/javascript">
  // $(document).ready(function() {
  //   var el = $(".err")
  //   el.removeClass("err");
  //   el.addClass("nx")
  // })
</script>

<div class="blog-partial">
  <div class="header-container">
    <h2><%= blog.title %></h2>
    <h4> <%= blog.updated_at.strftime("%B %d, %Y") %> </h4>
  </div>


  <div class="markdown-container">
    <%= markdown(@blog.body) %>
  </div>
</div>

<% if logged_in?(:site_admin) %>
  <div class="blog-admin-links">
    <%= link_to 'edit', edit_blog_path %>
    <br>
    <%= link_to 'delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <ul>
      <% blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="body">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 15 %>
  </div>

  <div class="project-selector">
    <h2 class="faux-label">Assign Project Id</h2>
    <%= f.number_field :project_id %>
  </div>

  <div class="actions">
    <%= f.submit %>

    <% if form_type == 'new' %>
      <%= link_to 'Cancel', root_path, data: { confirm: 'Edits will not be saved' }, class: "delete-link" %>
    <% elsif form_type == 'edit'%>
      <%= link_to "Delete", @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-link" %>
    <% end %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="blog-edit">
  <div class="blog-title">
    <h1>Edit <%= @blog.title %></h1>
  </div>

  <%= link_to 'Return to Blogs Index', blogs_path %>

  <%= render 'form', blog: @blog, form_type: 'edit', type: 'edit' %>
</div>

app/views/blogs/index.html.erb
<div class="blog-index">
  <%= render @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="blog-create">
  <div class="blog-title">
    <h1>Create New Blog</h1>
  </div>

  <%= link_to 'Return to Blogs Index', blogs_path %>

  <%= render 'form', blog: @blog, form_type: 'new', type: 'new' %>
</div>

app/views/blogs/show.html.erb
<div class="blog-show">
  <%= render @blog %>

  <div class="other-blogs">
    <h3>Other Posts</h3>
    <ul>
      <% @blogs.each do |blog| %>
       <% if blog == @blog %>
         <li><%= @blog.title %></li>
        <% else %>
          <li><%= link_to blog.title, blog %></li>
       <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>David Sawatske</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Raleway|Playfair+Display" rel="stylesheet">

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-119437845-2', 'auto');
      ga('send', 'pageview');
    </script>
  </head>

  <body>
    <div class="info-head">
      <h2 class="name"><%= link_to "David Sawatske", root_path %></h2>

      <div class='links'>
        <%= render "pages/contact" %>
      </div>
    </div>

    <div class="alert">
      <p><%= notice %></p>
      <p><%= alert %></p>
    </div>

    <div class="session">
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Admin Sign In", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/_contact.html.erb
<div class='contact'>
  <h2>Contact</h2>
  <ul>
    <li>
      <a href="mailto:david@sawatske.com">
        <%= image_tag("email.png") %>
      </a>
    </li>
    <li>
      <a target="_blank" href="https://linkedin.com/in/david-sawatske">
        <%= image_tag("linkedin.png") %>
      </a>
    </li>
    <li>
      <a target="_blank" href="https://github.com/david-sawatske">
        <%= image_tag("github.png") %>
      </a>
    </li>
    <li>
      <a target="_blank" href="https://angel.co/david-sawatske">
        <%= image_tag("angel.png") %>
      </a>
    </li>
    <li>
      <a target="_blank" href="https://drive.google.com/file/d/1Uq9n9sWQ-Kc7oNQpJZF5FkDS69k_w4Cd/view?usp=sharing">
        <%= image_tag("resume.png") %>
      </a>
    </li>
  </ul>
</div>

app/views/pages/home.html.erb
<div class='home-container'>
  <div class="project-overlay">

  </div>

  <div class='project-container'>
    <div class="project-list project-sort">
      <% @projects.each do |project| %>
          <h1 class="project-title" data-id="<%= project.id %>">
            <%= link_to project.title, project_path(project), id: project.id,
                                                              remote: true %>
          </h1>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <%= link_to "Create New Project", new_project_path, class: 'add-project' %>
      <% end %>
    </div>

    <div class="selected-project">
      <%= render @projects[0] if @projects[0] %>
    </div>
  </div>

  <div class='profile-container'>
    <%= image_tag("me.jpg", alt: "me", class: "profile-picture") %>

    <h1 class="hello"> Hi, I'm David.</h1>

    <div class="description">
      <p>
        I'm a software developer. Please have a look at my projects or get to know me below.
      </p>
    </div>

    <div class='about-me'>
      <h2> About Me </h2>
      <p>My principal experience is in building React/Redux apps with a Ruby on Rails backend. Check the list below for list of some of the technologies I'm most familiar with below.
        <br>
        <br>
      Please feel free to contact me if you are looking to connect or if interested in discussing opportunities. Thanks!
      </p>
    </div>

    <div class="skills-list">
      <h2>Skills</h2>
      <ul>
        <% @technologies.each do |tech| %>
          <li><%= tech.name %></li>
        <% end %>
      </ul>
    </div>

    <%= render "contact" %>
  </div>

  <div class="about-click">
    <h2> About </h2>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <div class="title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="description">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="proj-img">
    <label class="upload-btn">
      <h4><%= type.capitalize %> Image</h4>
      <%= f.file_field :image, class: 'image-upload', style: 'display:none;' %>
    </label>

    <%= image_tag '', class: 'img-prev' %>
    <% if @project.image? %>
      <%= image_tag @project.image, class: 'current-img' %>
    <% else %>
      <label class="add-img-btn">
        <%= image_tag 'add-img.png', class: 'current-img' %>
        <%= f.file_field :image, class: 'image-upload', style: 'display:none;' %>
      </label>
    <% end %>
  </div>

  <div class="technologies">
    <h2 class="faux-label">Technologies Used</h2>

    <%= f.fields_for :technologies do |tech_form| %>
      <%= render 'technology_fields', f: tech_form %>
    <% end %>

    <div class="add-tech">
      <%= link_to_add_association 'Add Technology', f, :technologies %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>

    <% if form_type == 'new' %>
      <%= link_to 'Cancel', root_path, data: { confirm: 'Edits will not be saved' }, class: "delete-link" %>
    <% elsif form_type == 'edit'%>
      <%= link_to "Delete", @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-link" %>
    <% end %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class='project'>
  <% if logged_in?(:site_admin) %>
    <h3><%= link_to project.title, edit_project_path(project) %></h3>
  <% else %>
  <h3><%= project.title %></h3>
  <% end %>

  <p class="project-description"><%= project.description %></p>

  <% if project.image? %>
    <%= image_tag project.image, class: "project-image" %>
  <% else %>
    <%= image_tag src="http://via.placeholder.com/200x150", class: "project-image" %>
  <% end %>

  <ul class="project-links">
    <% if project.live_url %>
      <li>
        <%= link_to_if project.live_url,
            image_tag("web-link.png", id: project.title),
            project.live_url,
            onclick: "ga('send', 'event', '#{project.title}', 'to Site');" %>
      </li>
    <% end %>

    <% if project.git_url %>
      <li>
        <%= link_to image_tag("github.png"),
            project.git_url,
            onclick: "ga('send', 'event', '#{project.title}', 'to GitHub');" %>
      </li>
    <% end %>
  </ul>

  <div class="project-technologies">
    <h4>Technologies: </h4>
    <ul>
      <% project.technologies.each do |tech| %>
        <li><%= image_tag tech.icon, class: "tech-icon" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/_technology_fields.html.erb
<div class="nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name %>

  <label class="icon-add">
    <% if f.object.icon? %>
      <%= image_tag f.object.icon_url, class: 'current-icon' %>
    <% else %>
      <%= image_tag 'add-img.png', class: 'current-icon' %>
    <% end %>
    <%= f.file_field :icon, class: 'icon-upload', style: 'display:none;' %>
  </label>

  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/projects/edit.html.erb
<div class="project-edit">
  <div class="project-title">
    <h1>Edit <%= @project.title %></h1>
  </div>

  <%= render 'form', project: @project, form_type: 'edit', type: 'edit' %>
</div>

app/views/projects/index.html.erb
<div class='project-index'>
  <h1>My Projects</h1>
  <p>
    <%= link_to "Create New Item", new_project_path %>
  </p>

  <%= render @projects %>
</div>

app/views/projects/new.html.erb
<div class="project-create">
  <div class="project-title">
    <h1>Display New Project</h1>
  </div>

  <%= render 'form', project: @project, form_type: 'new', type: "Select" %>
</div>

app/views/projects/show.js.erb
$('.selected-project')
  .html('<%= j render(@project) %>');